apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: apix
  app.kubernetes.io/name: apix
  app.kubernetes.io/part-of: apix-gateway
