apiVersion: apps/v1
kind: Deployment
metadata:
  name: apix
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: apix
          env:
            - name: APIX_LOG_LEVEL
              value: debug
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
