global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'apix'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apix:8081']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
