apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apix.fullname" . }}
  labels:
    {{- include "apix.labels" . | nindent 4 }}
data:
  config.yaml: |
    mode: {{ .Values.deployment.mode }}
    log_level: {{ .Values.apix.logLevel }}
    dbless: {{ .Values.apix.dbless }}
    
    admin:
      listen: 0.0.0.0:8001
    
    proxy:
      listen: 0.0.0.0:8000
    
    eventbus:
      cluster_name: {{ .Values.apix.eventBus.clusterName }}
      cluster_type: {{ .Values.apix.eventBus.clusterType }}
    
    plugins:
      enabled:
      {{- range .Values.apix.plugins.enabled }}
        - name: {{ .name }}
          config:
            {{- toYaml .config | nindent 12 }}
      {{- end }}
    
    {{- if .Values.apix.customConfig }}
    # Custom configuration
    {{- toYaml .Values.apix.customConfig | nindent 4 }}
    {{- end }}
