Args = --initialize-at-build-time=ch.qos,org.slf4j \
       --initialize-at-run-time=io.vertx.ext.web.client.WebClientOptions,io.netty.channel.epoll,io.netty.channel.unix,io.netty.handler.ssl \
       --no-fallback \
       --enable-http \
       --enable-https \
       --enable-url-protocols=http,https \
       --enable-all-security-services \
       --report-unsupported-elements-at-runtime \
       -H:+ReportExceptionStackTraces \
       -H:+PrintClassInitialization \
       -H:+RemoveSaturatedTypeFlows \
       -H:+StackTrace \
       -H:+JNI \
       -H:+AllowIncompleteClasspath \
       -H:IncludeResources=.*/vertx-.*.json \
       -H:IncludeResources=.*/vertx-.*.properties \
       -H:IncludeResources=.*/logback.xml \
       -H:IncludeResources=.*/apix.json \
       -H:IncludeResources=.*/vertx-high-performance.json \
       -H:IncludeResources=.*/vertx-ultra-performance.json \
       -H:IncludeResources=.*/config.json \
       -H:IncludeResources=.*/config/.* \
       -H:IncludeResources=.*/META-INF/.* \
       -H:+UseServiceLoaderFeature \
       --allow-incomplete-classpath \
       --install-exit-handlers \
       --enable-https \
       --enable-url-protocols=http,https,unix \
       --gc=serial \
       -H:+AddAllCharsets \
       -H:+InlineBeforeAnalysis \
       -H:+InlineDuringParsing \
       -H:+RemoveUnusedSymbols \
       -H:+FoldSecurityManagerGetter \
       -H:+TrustFinalDefaultFields \
       -Dio.netty.noUnsafe=false \
       -Dio.netty.leakDetection.level=disabled \
       -Dvertx.disableDnsResolver=true \
       -Dvertx.disableMetrics=true \
       -Dvertx.disableH2c=true \
       -Dvertx.disableWebsockets=false \
       -Dvertx.flashPolicyHandler=false \
       -Dvertx.threadChecks=false \
       -Dvertx.disableContextTimings=true \
       -Dvertx.disableTCCL=true \
       -Dvertx.disableHttpHeadersValidation=true \
       -Dvertx.eventLoopPoolSize=84 \
       -Dvertx.workerPoolSize=140 \
       -Dvertx.preferNativeTransport=true
