Args = --initialize-at-build-time=ch.qos,org.slf4j \
       --initialize-at-run-time=io.vertx.ext.web.client.WebClientOptions \
       --no-fallback \
       --enable-http \
       --enable-https \
       --enable-url-protocols=http,https \
       --report-unsupported-elements-at-runtime \
       -H:+ReportExceptionStackTraces
